dist: xenial
language: java
sudo: false
jdk: openjdk14
install: true
addons:
  sonarcloud:
    organization: Luiz Fernando Areas
    token: 44ce8874b5f45506de8a0e781a1656ae629ce6a7
script:
  - mvn clean package sonar:sonar -P sonar
cache:
  directories:
    - $HOME/.m2
    - $home/.sonar/cache
before_install:
  - chmod +x mvnw

